import type { Metadata } from "next";
import { Geist, Geist_Mono, Inter ,Plus_Jakarta_Sans, JetBrains_Mono, Elms_Sans} from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";
import { TooltipProvider } from "@/components/ui/tooltip"
import Sidenavbar from "@/components/sidebar";



const inter = Inter({subsets:['latin'],variable:'--font-sans'});

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});


const jakarta = Plus_Jakarta_Sans({ 
  subsets: ['latin'],
  variable: '--font-jakarta', 
})

const jetbrainsMono = JetBrains_Mono({ 
  subsets: ['latin'],
  variable: '--font-mono-custom', // Named slightly different to avoid conflicts
})


// 3. Initialize Elms Sans (Testing to see if it compiles)
const elms = Elms_Sans({
  subsets: ["latin"],
  variable: "--font-elms",
});

export const metadata: Metadata = {
  title: "Hamees",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
   <html lang="en" className={`${jakarta.variable} ${jetbrainsMono.variable} ${elms.variable}`}>
      <body className="font-sans antialiased bg-white dark:bg-black text-gray-900 dark:text-white">
        <TooltipProvider >
          
          <Sidenavbar />
          {children}
          
          </TooltipProvider>
      </body>
    </html>
  );
}
